spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edtech
    username: root
    password: akshay
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: "/Telusko"
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
